name: build-osx

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11 ]

    name: Build ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: go.sum

    - name: Check go install
      run: go version

    - name: Build universal binary
      run: |
        CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -tags static -o vstars2vice_amd64 .
        CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -tags static -o vstars2vice_arm64 .
        lipo -create -output vstars2vice vstars2vice_amd64 vstars2vice_arm64

    - name: Save executable
      uses: actions/upload-artifact@v3
      with:
        name: vstars2vice
        path: vstars2vice

    - name: Upload release (maybe)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      permissions:
        contents: write            
      with:
        files: 'vstars2vice'
